SCHEMA_VERSION = "0.1.0"

STATUS_VALUES = {
    "present",
    "absent",
    "suspected",
    "rule_out",
    "historical",
    "resolved",
    "normal",
    "abnormal",
    "not_reported",
}

DOG_SUMMARY_COLUMNS = [
    "dog_id",
    "source_report_id",
    "source_file",
    "extraction_status",
    "dog_name",
    "species",
    "breed_raw",
    "breed_primary",
    "mixed_breed_status",
    "sex_raw",
    "sex",
    "reproductive_status",
    "date_of_birth",
    "age_reported",
    "age_years_at_report",
    "coat_color",
    "microchip_id_present",
    "rabies_tag_or_id_present",
    "source_facility",
    "evidence_quote",
    "schema_version",
]

VISIT_COLUMNS = [
    "visit_id",
    "dog_id",
    "source_report_id",
    "source_file",
    "visit_date",
    "document_date",
    "visit_type",
    "visit_reason_raw",
    "chief_complaint_normalized",
    "age_at_visit_years",
    "weight_lb",
    "weight_kg",
    "body_condition_score",
    "body_condition_scale",
    "muscle_condition_score",
    "pain_score",
    "pain_score_scale",
    "temperature_f",
    "heart_rate_bpm",
    "respiratory_rate_bpm",
    "crt_seconds",
    "mucous_membrane_color",
    "hydration_status",
    "mentation_attitude",
    "current_medications_raw",
    "current_diet_raw",
    "environment_exposure_raw",
    "general_appearance_exam",
    "eyes_exam",
    "ears_exam",
    "nose_exam",
    "oral_dental_exam",
    "skin_coat_exam",
    "lymph_nodes_exam",
    "cardiovascular_exam",
    "respiratory_exam",
    "abdomen_gi_exam",
    "urogenital_exam",
    "perineal_anal_gland_exam",
    "musculoskeletal_gait_exam",
    "neurologic_exam",
    "rectal_exam",
    "evidence_quote",
    "page_number",
    "confidence",
    "schema_version",
]

EVENT_COLUMNS = [
    "event_id",
    "dog_id",
    "visit_id",
    "source_report_id",
    "source_file",
    "visit_date",
    "phenotype_id",
    "status",
    "value_raw",
    "value_normalized",
    "unit",
    "body_site",
    "laterality",
    "severity",
    "duration",
    "onset_date",
    "resolved_date",
    "temporality",
    "negation",
    "source_sentence",
    "page_number",
    "confidence",
    "needs_review",
    "schema_version",
]

LAB_COLUMNS = [
    "lab_result_id",
    "dog_id",
    "visit_id",
    "source_report_id",
    "source_file",
    "collection_date",
    "source_panel",
    "specimen",
    "analyte_raw",
    "analyte_normalized",
    "value_raw",
    "value_numeric",
    "unit",
    "reference_low",
    "reference_high",
    "flag",
    "source_sentence",
    "page_number",
    "confidence",
    "schema_version",
]

DIAG_COLUMNS = [
    "diagnostic_event_id",
    "dog_id",
    "visit_id",
    "source_report_id",
    "source_file",
    "event_date",
    "diagnostic_type",
    "status",
    "body_site",
    "result_summary",
    "source_sentence",
    "page_number",
    "confidence",
    "schema_version",
]

MED_COLUMNS = [
    "medication_event_id",
    "dog_id",
    "visit_id",
    "source_report_id",
    "source_file",
    "event_date",
    "medication_name_raw",
    "medication_class",
    "status",
    "dose_raw",
    "route_raw",
    "frequency_raw",
    "source_sentence",
    "page_number",
    "confidence",
    "schema_version",
]

PROC_COLUMNS = [
    "procedure_event_id",
    "dog_id",
    "visit_id",
    "source_report_id",
    "source_file",
    "event_date",
    "procedure_type",
    "status",
    "body_site",
    "source_sentence",
    "page_number",
    "confidence",
    "schema_version",
]

CANDIDATE_COLUMNS = [
    "candidate_id",
    "dog_id",
    "source_report_id",
    "source_file",
    "candidate_name",
    "suggested_category",
    "evidence_quote",
    "page_number",
    "rationale",
    "schema_version",
]

TABLE_COLUMNS = {
    "dog_summary.csv": DOG_SUMMARY_COLUMNS,
    "visit_summary.csv": VISIT_COLUMNS,
    "phenotype_events.csv": EVENT_COLUMNS,
    "lab_results.csv": LAB_COLUMNS,
    "diagnostic_events.csv": DIAG_COLUMNS,
    "medication_events.csv": MED_COLUMNS,
    "procedure_events.csv": PROC_COLUMNS,
    "new_candidate_phenotypes.csv": CANDIDATE_COLUMNS,
}
